import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "invalidPassword": "Invalid mobile/password",
          "ok": "OK",
          "cancel": "Cancel",
          "mon": "MON",
          "tue": "TUE",
          "wed": "WED",
          "thu": "THUR",
          "fri": "FRI",
          "sat": "SAT",
          "sun": "SUN",

          "Opened": "Opened",
          "MostRate": "Most Rate",
          "TopRate": "Top Rate",
          "NearBy": "Near By",

          "SelectCity": "Select City",
          "KM": "KM",
          "Filters": "Filters",
          "NoDataAvailable": "No Data Available",
          "Monday": "Monday",
          "Tuesday": "Tuesday",
          "Wednesday": "Wednesday",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Satureday": "Satureday",
          "Sunday": "Sunday",
          "ClosedNow": "Closed Now",
          // "OpenNow": "Open Now",
          "Pending": "Pending",
          "Confirmed": "Confirmed",
          "All": "All",
          "Availed": "Availed",
          "Rejected": "Rejected",
          "Completed": "Completed",

          "Cancelled": "Cancelled",
          "ChangeLanguage": "عربى",
          "Month": "Month",
          "Months": "Months",
          "ThisFeatureWillBeAvailableSoon":
              "This Feature Will Be Available Soon",
          "DataUpdated": "Data Updated",
          "RateProducts": "Rate Products",
          "RateEmployee": "Rate Employee",
          "RateSaloon": "Rate Saloon",
          "Ratting": "Rating",
          "Rate": "Rate",
          "ProductsRatting": "Products Rating",
          "SaloonRatting": "Saloon Rating",

          "EmployeeRatting": "Employee Rating",

//////auth
          "SignIn": "Sign In",
          "SignUp": "Sign Up",
          "LoginAsGuest": "Login As Guest",
          "EnterMobileNo": "Enter Mobile No",
          "ForgetPassword": "Forget Password",

          'Beauty Queens': 'Beauty Queens',
          "EnterPassword": "Enter Password",
          "Login": "Login",
          "Submit": "Submit",
          "OTPScreen": "OTP Screen",
          "ReEnterPassword": "Re - Enter Password",
          "SetPassword": "Set Password",
          "InvalidPhoneNumber": "Invalid Phone Number",
          "EnterName": "Enter Name",

          // ///////drawer
          "NoAppointmentsAvailable": "No appointments available",
          "MyAppointments": "My Appointments",
          "Notifications": "Notifications",
          "NoNotificationsAvailable": "No notifications available",
          "Profile": "Profile",
          "Name": "Name:",
          "Email": "Email",
          "MobileNo": "Mobile No:",
          "Update": "Update",
          "OfferDetails": "Offer Details",
          "Expiry": "Expiry",
          "Description": "Description:",
          "Contact": "Contact",
          "Whatsapp": "Whatsapp",
          "Location": "Location",
          "Offers": "Offers",
          "Cart": "Cart",
          "CartIsEmpty": "Cart is empty",
          "AppointmentDate": "Select Your Date",
          "enterTime": "Select Your Time",
          "ChooseEmployee": "Choose Employee",
          "Number": "No:",
          "ServiceName": "Service Name",
          "Time": "Time",
          "Time:": "Time:",
          "Price": "Price",
          "OMR": "OMR",
          "Services:": "Services:",
          "Amount:": "Amount:",
          "Checkout": "Checkout",
          // //////dasboard
          "BeautyCentres": "Beauty Centres",
          "SPA": "SPA",
          "LadiesGym": "Ladies Gym",
          "BeautyProducts": "Beauty Products",
          "JoinUs": "Join Us",
          "Call": "Call",
          // "OpenNow": "Open Now",
          "Packages": "Packages",
          "BeautyProductsShops": "Beauty Products Shops",
          "Minutes": "Minutes",
          "Employees": "Employee",
          "ViewEmployees": "View Employees",
          "BeautyCenters": "Beauty Centers",
          "Appointment#:": "Appointment #:",
          "SaloonName": "Saloon Name",
          "Date": "Date",
          "Status": "Status",
          "TotalServices": "Total Services",
          "TotalAmount": "Total Amount",
          "Employess": "Employess",
          "GuestUser": "Guest User",
          "ChangePassword": "Change Password",
          "Logout": "Logout",
          "logout_alert": "Are you sure you want to logout?",
          "language_alert": "Are you sure you want to change language?",
          "delete_alert": "Are you sure you want to delete your account?",

          "Yes": "Yes",
          "DeleteAccount": "Delete Account",
          "WillAvailableSoon": "Will available soon",
          "Change Language to   عربى": "عربى",
          "OK": "OK",
          "Discount": "Discount",
          "Years": "years",
          "cart_add_other_saloon_service_alert":
              "You have added other saloon service. Are you sure you want to clear cart to add new services",
          "Cancel": "Cancel",
          "ClearCart": "Clear Cart",
          ///////////alert toasts
          "valid_number_alert": "Please Enter a valid mobile number",
          "valid_password_alert": "Please Enter password",
          "valid_name_alert": "Please Enter Name",
          "PasswordMismatch": "Password mismatch",
          "ThisNumberAlreadyExist": "This number already exist ",
          "CartHasBeenClearedSuccessfully":
              "Cart has been cleared successfully",
          "AddedToCart": "Added to cart",
          "PleaseSelectAppointmentDateTime":
              "Please select appointment date time",
          "PleaseSelectEmployee": "Please select employee",
          "PleaseSelectServices": "Please select services",
          "AppointmentSuccessToast":
              "Your appointment request has been submitted successfully. You will be notified after accept",

          "LoggedInSuccessfully": "Logged in successfully",
          // /////statuses
        },
        'ar': {
          "invalidPassword": "رقم الهاتف او كلمة المرور غير صحيحة",
          "ok": "نعم",
          "cancel": "إلغاء",
          "mon": "الاثنين",
          "tue": "الثلاثاء",
          "wed": "الأربعاء",
          "thu": "الخميس",
          "fri": "جمعة",
          "sat": "السبت",
          "sun": "الأحد",
          "Opened": "مفتوح",
          // "NearBy": "بالقرب مني",
          // "TopRate": "أعلى معدل",
          // "MostRate": "الأكثر معدل",
          // "OpenNow": "مفتوح الان",
          // "ClosedNow": "مغلق الآن",
          // "Monday": "الاثنين",
          // "Tuesday": "الثلاثاء",
          // "Wednesday": "الأربعاء",
          // "Thursday": "الخميس",
          // "Friday": "جمعة",
          // "Satureday": "يوم السبت",
          // "Sunday": "الأحد",
          // "SelectCity": "اختر مدينة",
          // "KM": "كيلو متر",
          // "Filters": "المرشحات",
          // "NoDataAvailable": "لا تتوافر بيانات",

//////auth
          "SignIn": "دخول",
          "SignUp": "التسجيل",
          "LoginAsGuest": "زائرة للتطبيق",
          "EnterMobileNo": "أدخلي رقم الهاتف",
          "ForgetPassword": "نسيت كلمة السر",

          'Beauty Queens': 'ملكات الجمال',
          "EnterPassword": "أدخلي كلمة السر",
          "Login": "دخول",
          "Submit": "ارسال",
          "OTPScreen": "OTP رمز",
          "ReEnterPassword": "أعيدي إدخال كلمة السر",
          "SetPassword": "ضعي كلمة السر",
          "InvalidPhoneNumber": "رقم هاتف غير صحيح",
          "EnterName": "أدخلي اسمك",

          // ///////drawer
          "NoAppointmentsAvailable": "لا توجد مواعيد",
          "MyAppointments": "مواعيدي",
          "Notifications": "الإشعارات",
          "NoNotificationsAvailable": "لا توجد إشعارات",
          "Profile": "الملف الشخصي",
          "Name": "الاسم:",
          "Email": "البريد الإلكتروني",
          "MobileNo": "رقم الهاتف:",
          "Update": "تحديث",
          "OfferDetails": "بيانات العرض",
          "Expiry": "الإنتهاء",
          "Description": "الوصف:",
          "Contact": "التواصل",
          "Whatsapp": "وتس آب",
          "Location": "الموقع",
          "Offers": "عروض",
          "Cart": "السلة",
          "CartIsEmpty": "سلة الخدمات فارغة",
          "AppointmentDate": "تاريخ الموعد",
          "enterTime": "حدد وقتك",
          "ChooseEmployee": "اختاري خبيرة التجميل",
          "Number": "لا:",
          "ServiceName": "اسم الخدمة",
          "Time": "الوقت",
          "Time:": "الوقت:",
          "Price": "السعر",
          "OMR": "ر.ع",
          "Services:": "الخدمات:",
          "Amount:": "المبلغ:",
          "Checkout": "تأكيد الموعد",
          // //////dasboard
          "BeautyCentres": "مراكز التجميل",
          "SPA": "سبا",
          "LadiesGym": "الصالات الرياضية النسائية",
          "BeautyProducts": "منتجات التجميل",
          "JoinUs": "انضمي الينا",
          "Call": "اتصال",
          "OpenNow": "مفتوح الآن",
          "Packages": "الباقات",
          "BeautyProductsShops": "مراكز منتجات التجميل",
          "Minutes": "دقائق",
          "Employees": "خبيرات التجميل",
          "ViewEmployees": "معاينة خبيرات التجميل",
          "BeautyCenters": "مراكز التجميل",
          "Appointment#:": "المواعيد #:",
          "SaloonName": "اسم مركز التجميل",
          "Date": "التاريخ",
          "Status": "الحالة",
          "TotalServices": "اجمال الخدمات",
          "TotalAmount": "المبلغ الإجمالي",
          "Employess": "خبيرات التجميل",
          "GuestUser": "زائرة للتطبيق",
          "ChangePassword": "تغيير كلمة السر",
          "Logout": "خروج",
          "delete_alert": "هل انتي متاكدة من حذف حسابك؟ ",
          "logout_alert": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
          "language_alert": "هل أنت متأكد أنك تريد تغيير اللغة؟",
          "Yes": "نعم",
          "DeleteAccount": "حذف الحساب",
          "WillAvailableSoon": "سيكون متوفر قريباً",
          "Change Language to   عربي": "English",
          "OK": "موافق",
          "Discount": "تخفيض",
          "Years": "السنة",
          "cart_add_other_saloon_service_alert":
              "لقد قمتي بإضافة خدمة صالون أخرى. هل أنتي متأكدة أنك تريدي مسح سلة الخدمات لإضافة خدمات جديدة",
          "Cancel": "الغاء",
          "ClearCart": "مسح سلة الخدمات",
          ///////////alert toasts
          "valid_number_alert": "ادخلي رقم هاتف صحيح",
          "valid_password_alert": "ادخلي كلمة السر",
          "valid_name_alert": "ادخلي اسمك",
          "PasswordMismatch": "كلمة السر غير متطابقة",
          "ThisNumberAlreadyExist": "عذرا  الرقم مسجل مسبقاً ",
          "CartHasBeenClearedSuccessfully": "تم مسح سلة الخدمات بنجاح",
          "AddedToCart": "إضافة الى سلة الخدمات",
          "PleaseSelectAppointmentDateTime":
              "الرجاء تحديد الموعد  التاريخ  الوقت",
          "PleaseSelectEmployee": "اختاري خبيرة التجميل",
          "PleaseSelectServices": "اختاري الخدمة",
          "AppointmentSuccessToast":
              "تم تقديم طلب موعدك بنجاح. سيتم إخطارك بعد تأكيد الموعد",

          "LoggedInSuccessfully": "تم تسجيل الدخول بنجاح",
          // /////statuses
          // "Pending": "قيد الانتظار",
          // "All": "الجميع",
          // "Confirmed": "مؤكد",
          // "Availed": "تمت الزيارة",
          // "Rejected": "مرفوض",
          // "Cancelled": "ملغي",

          // "Completed": "مكتمل",
          // "ChangeLanguage": "English",
          // "Month": "شهر",
          // "Months": "شهور",
          // "DataUpdated": "تم تحديث البيانات",
          // "ThisFeatureWillBeAvailableSoon": "ستتوفر هذه الميزة قريبًا",
          // "Ratting": "الضرب",
          // "RateSaloon": "قيم الصالون",
          // "RateEmployee": "معدل الموظف",
          // "RateProducts": "قيم المنتجات",
          // "EmployeeRatting": "الموظف الخشخاش",
          // "SaloonRatting": "قعقعة الصالون",
          // "ProductsRatting": "المنتجات الخشخشة",
          // "Rate": "معدل",

          "MostRate": "الاكثر تقييما",
          "TopRate": "الافضل تقييما",
          "NearBy": "قريب مني",

          "SelectCity": "اختر المدينة",
          "KM": "كم",
          "Filters": "الفرز",
          "NoDataAvailable": "لا توجد بيانات",
          "Monday": "الاثنين",
          "Tuesday": "الثلاثاء",
          "Wednesday": "الاربعاء",
          "Thursday": "الخميس",
          "Friday": "الجمعة",
          "Satureday": "السبت",
          "Sunday": "الاحد",
          "ClosedNow": "مغلق",
          // "OpenNow": "مفتوح",
          "Pending": "قيد الانتظار",
          "Confirmed": "مؤكد",
          "All": "الجميع",
          "Availed": "تمت الزيارة",
          "Rejected": "مرفوض",
          "Completed": "مكتمل",

          "Cancelled": "ملغي",
          "ChangeLanguage": " English ",
          "Month": "شهر",
          "Months": "شهور",
          "ThisFeatureWillBeAvailableSoon": "هذه الخدمة ستتوفر قريبا",
          "DataUpdated": "تم تحديث البيانات",
          "RateProducts": "قيم المنتجات ",
          "RateEmployee": "قيم الموظفة",
          "RateSaloon": "قيم مركز التجميل",
          "Rating": "التقييم",
          "Rate": "قيم",
          "ProductsRatting": "تقييمات المنتجات",
          "SaloonRatting": "تقييمات مركز التجميل",

          "EmployeeRatting": "تقييمات الموظفين",
        },
      };
}
